docker rmi frankenstein-app
docker rmi frankenstein-gateway
docker rmi frankenstein-opcua
docker rmi frankenstein-plc4x
docker rmi frankenstein-dds
docker rmi frankenstein-cache
docker rmi frankenstein-influxdb
docker rmi frankenstein-iotdb
docker rmi frankenstein-kafka