Drivers:
  Mqtt:
    - Id: "home"
      Enabled: true
      LogLevel: INFO
      Host: 192.168.1.4
      Port: 1883
      ClientId: frankenstein-driver-test
      Format: Json
      CustomJson:
        Value: "Value"
        TimestampMs: "TimeMS"
        TimestampIso: "TimeISO"

Loggers:
  Snowflake:
    - Id: "snowflake"
      Enabled: true
      LogLevel: INFO
      PrivateKeyFile: "security/snowflake.p8"
      Account: ig92018
      Url: https://ig92018.eu-central-1.snowflakecomputing.com:443
      User: vogler
      Role: accountadmin
      Scheme: https
      Port: 443
      Database: SCADA
      Schema: SCADA
      Table: GATEWAY
      Logging:
        - Topic: mqtt/home/path/Original/#
