module org {
  module omg {
    module dds {
      module demo {
        @topic
        struct ShapeType {
          @key string color;
          long x;
          long y;
          long shapesize;
        };

        @topic
        struct Message {
          string from;
          string subject;
          @key long subject_id;
          string text;
          unsigned long count;
        };
      };
    };
  };
};

